name: Flatpak

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  flatpak:
    name: Bundle
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50@sha256:1de59efef01a946d9f28f1ec3458bf6f61dcee3507d7fecdd473f8134da4ec77
      options: --privileged
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: flatpak/flatpak-github-actions/flatpak-builder@79327416609af08178ad73b352877e51450790b3 # v6.8
        with:
          bundle: ferry.flatpak
          manifest-path: build-aux/io.github.mehmetnuri.Ferry.json
          cache: false
